import Image from "next/image";
import Header from "@/layouts/Header";

import Footer from "@/layouts/Footer";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Autoplay, Navigation, Pagination } from "swiper";
import Head from "next/head";
import TravelKitAmenity from "@/components/TravelKitAmenity";
import Contact from "@/components/Contact";
import BackButton from "@/components/BackButton";

export default function BAE146Series() {
  return (
    <>
      <Head>
        <title>JetBizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicon/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicon/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicon/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicon/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicon/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicon/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/favicon/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicon/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicon/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicon/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <Header />

      <main>
        <section>
          <div className="min-h-screen bg-white py-20 text-semi-black">
            <figure className="relative">
              <img
                src={"https://jetbizzaviation.com/images/Jets/BAE 146/BAe-146.jpg"}
                className="h-[300px] object-cover object-center w-full"
              />
              <div className="absolute h-full w-full top-0 left-0 bg-gradient-to-r from-slate-700 to-transparent"></div>

              <div className="absolute top-0 h-full w-full flex justify-center items-center">
                <h1 className="text-5xl text-light-gray font-semibold">
                  BAE 146 Series
                </h1>
              </div>
            </figure>

            {/* Overlay */}
            <div className="flex justify-end">
              <BackButton href="../all-deals" />
            </div>
            <div className="bg-white max-w-screen-xl mx-auto my-20 grid lg:grid-cols-2 sm:grid-col-1 gap-10">
              <div className="relative">
                <img
                  src={"https://jetbizzaviation.com/images/service-background-shape.png"}
                  className="absolute -top-10 -left-8 z-0 sm:hidden lg:block"
                />
                <img
                  src={"https://jetbizzaviation.com/images/Jets/BAE 146/bae_146_200-int-1-1024x679.jpg"}
                  className="absolute top-0 hidden lg:block left-0 z-10 aspect-[20/10] w-auto object-cover object-center rounded-lg shadow-lg"
                />
              </div>
              <div className="flex flex-col justify-center px-10 lg:px-0">
                <div className="text-sm font-bold">
                  <h1 className="text-5xl leading-tight mb-4">Overview</h1>
                </div>
                <div className="space-y-2 mb-4 text-base leading-relaxed tracking-wide">
                  <p>
                    The British Aerospace 146 is a short-haul and regional
                    airliner that was manufactured in the United Kingdom by
                    British Aerospace, later part of BAE Systems. Production ran
                    from 1983 until 2001. Manufacture by Avro International
                    Aerospace of an improved version known as the Avro RJ began
                    in 1992.
                  </p>
                </div>
              </div>
            </div>
            {/* Overlay */}

            {/* Specification List */}
            <div className="w-full py-20 lg:px-32 px-10">
              <div className="text-sm font-bold text-center">
                <p className="uppercase">
                  Jet <span className="text-gold">Specification</span>
                </p>
                <h1 className="text-5xl leading-tight mb-4">BAE 146 Series</h1>
              </div>
              <div className="overflow-auto">
                <table className="table border-collapse border border-slate-300 sm:w-full rounded-lg shadow-lg xs:w-[150%]">
                  <thead>
                    <tr>
                      <th className="p-4">#</th>
                      <th className="p-4">BAE 146-100</th>
                      <th className="p-4">BAE 146-200</th>
                      <th className="p-4">BAE 146-300</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Seats</th>
                      <td className="text-center">70 - 82</td>
                      <td className="text-center">85 - 100</td>
                      <td className="text-center">97 - 112</td>
                    </tr>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Cabin</th>
                      <td colSpan={3} className="text-center">
                        342m (11.2 ft
                      </td>
                    </tr>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Fuel</th>
                      <td colSpan={3} className="text-center">
                        11.728 L
                      </td>
                    </tr>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Speed</th>
                      <td colSpan={3} className="text-center">
                        Mach 0.739
                      </td>
                    </tr>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Takeoff SL</th>
                      <td className="text-center">3921 ft</td>
                      <td className="text-center">4560 ft</td>
                      <td className="text-center">5036 ft</td>
                    </tr>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Landing SL</th>
                      <td className="text-center">3870 ft</td>
                      <td className="text-center">3900 ft</td>
                      <td className="text-center">4170 ft</td>
                    </tr>
                    <tr className="border border-slate-300">
                      <th className="p-3 text-left">Fuel Consumption</th>
                      <td className="text-center">5441 Lb/h</td>
                      <td className="text-center">5474 Lb/h</td>
                      <td className="text-center">5549 Lb/h</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            {/* Specification List */}

            {/* Jet Gallery */}
            <div className="w-full bg-light-gray py-20">
              <div className="text-center">
                <p className="text-sm uppercase font-bold">
                  Jet <span className="text-gold">Gellery</span>
                </p>
                <h1 className="text-4xl font-bold my-4">
                  BAE 146 Series Photo Gallery
                </h1>
              </div>
              <div className="xs:px-10 sm:px-32 flex justify-center items-center">
                <Swiper
                  spaceBetween={30}
                  loop={true}
                  autoplay={{
                    delay: 2500,
                  }}
                  breakpoints={{
                    640: {
                      slidesPerView: 1,
                    },
                    1024: {
                      slidesPerView: 2,
                    },
                  }}
                  modules={[Autoplay, Pagination, Navigation]}
                >
                  <SwiperSlide>
                    <img
                      src={"https://jetbizzaviation.com/images/Jets/BAE 146/BAe-146.jpg"}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={"https://jetbizzaviation.com/images/Jets/BAE 146/bae_146_200-int-1-1024x679.jpg"}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={
                        "https://jetbizzaviation.com/images/Jets/BAE 146/Microsoft-Flight-Simulator-3-3.webp"
                      }
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={"https://jetbizzaviation.com/images/Jets/BAE 146/BAe-146.jpg"}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={"https://jetbizzaviation.com/images/Jets/BAE 146/bae_146_200-int-1-1024x679.jpg"}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={
                        "https://jetbizzaviation.com/images/Jets/BAE 146/Microsoft-Flight-Simulator-3-3.webp"
                      }
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
            {/* Jet Gallery */}

            {/* Travel Kit Amenity */}
            <TravelKitAmenity />
            {/* Travel Kit Amenity */}

            <Contact />
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
