import Image from "next/image";
import Header from "@/layouts/Header";

import Footer from "@/layouts/Footer";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Autoplay, Navigation, Pagination } from "swiper";
import Head from "next/head";
import TravelKitAmenity from "@/components/TravelKitAmenity";
import Contact from "@/components/Contact";

export default function MedicalEvacuation() {
  return (
    <>
      <Head>
        <title>JetBizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section>
          <div className="min-h-screen bg-white py-20 text-semi-black">
            <figure className="relative">
              <img
                src={'images/Medical Evacuation/AIR-AMBULANCE-medical-flights.jpg'}
                className="h-[300px] aspect-[2/1] w-full object-cover object-center"
              />
              <div className="absolute h-full w-full top-0 left-0 bg-gradient-to-r from-slate-700 to-transparent"></div>

              <div className="absolute top-0 h-full w-full flex justify-center items-center">
                <h1 className="text-5xl text-light-gray font-semibold">
                  Medical Evacuation
                </h1>
              </div>
            </figure>

            {/* Overlay */}
            <div className="bg-white max-w-screen-xl mx-auto my-20 grid lg:grid-cols-2 sm:grid-col-1 gap-10">
              <div className="relative">
                <img
                  src={'images/service-background-shape.png'}
                  className="absolute -top-10 -left-8 z-0 sm:hidden lg:block"
                />
                <img
                  src={'images/Medical Evacuation/Air-medical-transport-JetOptions-Private-Jets.jpg'}
                  className="absolute top-0 left-0 z-10 aspect-[1/1] max-w-full max-h-full object-cover object-center rounded-lg shadow-lg"
                />
              </div>
              <div className="flex flex-col justify-center sm:px-20 lg:px-0">
                <div className="text-sm font-bold">
                  <p className="uppercase text-gold">Executive</p>
                  <h1 className="text-5xl leading-tight mb-4">
                    Medical Evacuation
                  </h1>
                </div>
                <div className="space-y-2 mb-4 text-base leading-relaxed tracking-wide">
                  <p>
                    We have access to a dedicated, specially built global
                    network medical aircraft for all types of air ambulance
                    missions
                  </p>
                  <p>
                    Help those who are seriously injured abroad and supply
                    leaders insurance company
                  </p>
                  <p>
                    When your organization needs emergency assistance
                    transportation and time are essence, we move patients smooth
                    and fast
                  </p>
                </div>
                {/* <div>
                  <ul className="grid lg:grid-cols-2 sm:grid-cols-1 space-y-4">
                    <li className="flex justify-start items-start space-x-2">
                      <div>
                        <svg
                          className="bg-gold rounded-full h-6 w-6 text-light-gray"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {" "}
                          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />{" "}
                          <polyline points="22 4 12 14.01 9 11.01" />
                        </svg>
                      </div>
                      <div>
                        It’s not just about Jets, we can provide limousines,
                        people carriers, mini-bus and coach services
                      </div>
                    </li>
                    <li className="flex justify-start items-start space-x-2">
                      <div>
                        <svg
                          className="bg-gold rounded-full h-6 w-6 text-light-gray"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {" "}
                          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />{" "}
                          <polyline points="22 4 12 14.01 9 11.01" />
                        </svg>
                      </div>
                      <div>
                        We only supply quality cars such as Audi, Mercedes,
                        Limousine with professional chauffeurs
                      </div>
                    </li>
                    <li className="flex justify-start items-start space-x-2">
                      <div>
                        <svg
                          className="bg-gold rounded-full h-6 w-6 text-light-gray"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {" "}
                          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />{" "}
                          <polyline points="22 4 12 14.01 9 11.01" />
                        </svg>
                      </div>
                      <div>
                        We can arrange a luxury transfer to take you to the
                        airport, and when you arrive at your destination, an
                        onward ground transfer wherever you are in the world
                      </div>
                    </li>
                    <li className="flex justify-start items-start space-x-2">
                      <div>
                        <svg
                          className="bg-gold rounded-full h-6 w-6 text-light-gray"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {" "}
                          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />{" "}
                          <polyline points="22 4 12 14.01 9 11.01" />
                        </svg>
                      </div>
                      <div>
                        Your personal chauffeur will pick you up at home, your
                        hotel or office, and take you directly to the airport
                      </div>
                    </li>
                    <li className="flex justify-start items-start space-x-2">
                      <div>
                        <svg
                          className="bg-gold rounded-full h-6 w-6 text-light-gray"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {" "}
                          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />{" "}
                          <polyline points="22 4 12 14.01 9 11.01" />
                        </svg>
                      </div>
                      <div>
                        In difficult to reach places for example Ski resorts,
                      </div>
                    </li>
                    <li className="flex justify-start items-start space-x-2">
                      <div>
                        <svg
                          className="bg-gold rounded-full h-6 w-6 text-light-gray"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {" "}
                          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />{" "}
                          <polyline points="22 4 12 14.01 9 11.01" />
                        </svg>
                      </div>
                      <div>
                        Private Islands, Country House Hotels etc, we can
                        provide a onward helicopter transfer
                      </div>
                    </li>
                  </ul>
                </div> */}
              </div>
            </div>
            {/* Overlay */}

            {/* Jet Gallery */}
            {/* <div className="w-full bg-light-gray py-20">
              <div className="text-center">
                <p className="text-sm uppercase font-bold">
                  Jet <span className="text-gold">Gellery</span>
                </p>
                <h1 className="text-4xl font-bold my-4">
                  Bell 407 Photo Gallery
                </h1>
              </div>
              <div className="px-32 flex justify-center items-center">
                <Swiper
                  spaceBetween={30}
                  loop={true}
                  autoplay={{
                    delay: 2500,
                  }}
                  breakpoints={{
                    640: {
                      slidesPerView: 1,
                    },
                    1024: {
                      slidesPerView: 2,
                    },
                  }}
                  modules={[Autoplay, Pagination, Navigation]}
                >
                  <SwiperSlide>
                    <img
                      src={Bell1}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={Bell2}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={Bell3}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={Bell1}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={Bell2}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src={Bell3}
                      className="aspect-[2/1] bg-center bg-cover"
                    />
                  </SwiperSlide>
                </Swiper>
              </div>
            </div> */}
            {/* Jet Gallery */}

            <Contact />
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
