import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Image1 from "../public/images/Jets/Hawker-400XP/beechcraft-hawker-400xp.jpg";
import Image2 from "../public/images/Jets/Hawker 800XP/hawker-800xp-Exterior-NEW-jS.jpg";
import Image3 from "../public/images/Helicopters/BELL 407/helicopter-bell_407-1024x768.jpg";
import Image4 from "../public/images/Helicopters/BELL 412/Bell-412EP-e1427082029160-1200x718.jpg";
import Image5 from "../public/images/shutterstock_337284917-min.png";
import Image6 from "../public/images/close-up-photo-good-looking-man-casual-outfit-who-is-smiling-while-typing-something-his-laptop-holding-smartphone-his-left-hand-flying-first-class-plane-min.png";
import Image7 from "../public/images/Exclusive-and-Luxury-Transfer/Private-Jet-Luxurious-Travel-700x466-1.jpg";
import Image8 from "../public/images/Medical Evacuation/Air-medical-transport-JetOptions-Private-Jets.jpg";

import Header from "../layouts/Header";
import Footer from "../layouts/Footer";
import CardImage from "../components/CardImage";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>JetBizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        {/* Section 1 */}
        <section id="home">
          <section id="parallax">
            <section id="parallax-content">
              <p>#1 Private Jet Charter</p>
              <h1 className="text-5xl font-semibold">
                Indonesian Private Charter with Global Coverage
              </h1>

              <p>
                JetBizz is one of exclusive aviation services in Indonesia. Our
                professional focus is providing our clients exceptional jet
                charter service through making every air travel experience as
                time saving, enjoyable, and cost-effective as possible.
              </p>

              <div>
                <button>Our Service</button>
              </div>
            </section>
          </section>
        </section>
        {/* Section 1 */}

        {/* Section 2 */}
        <section id="pages">
          <div id="overlay">
            <div id="overlay-image">
              <div id="overlay-1"></div>
              <div id="overlay-2"></div>
            </div>
            <div id="overlay-text">
              <p className="text-lg">Why Choose Us</p>

              <h1 className="text-4xl">Why Choose a Private Jet Charter?</h1>

              <p className="my-6 font-semibold">
                We provide aircraft charters to business professionals, to
                maximise their time efficiency. Today we provide aircraft
                charters to business professionals, to maximise their time
                efficiency.
              </p>

              <p className="my-6">
                As well as getting to fly to many different destinations as part
                of their job, airplane pilots get big discounts on, As well as
                getting to fly to many different destinations as part of their
                job, airplane pilots get big discounts on
              </p>

              <div id="overlay-text-list">
                <ul>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Flexible Schedule</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Excellent Advantages</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Save Your Time</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Luxury and Comfort</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>

                      <p>Safety and Confidential</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Many Airports</p>
                    </div>
                  </li>
                </ul>
              </div>

              <div className="my-6">
                <button className="">Our Service</button>
              </div>
            </div>
          </div>
        </section>
        {/* Section 2 */}

        {/* Section 3 */}
        <section id="service">
          <div id="section-3-1">
            <div className="font-bold">
              <p className="text-sm uppercase">
                Our <span className="text-gold">Services</span>
              </p>
              <h1 className="text-4xl font-semibold mb-10">
                Find The Best Service <br /> For You
              </h1>
            </div>
            <div>
              <div className="grid lg:grid-cols-2 sm:grid-cols-2 mx-auto gap-4 xl:w-2/3">
                <CardImage
                  src={Image7}
                  href="./views/executive-and-luxury-transfer"
                  product="Exclusice and Luxury Transfer"
                  alt="Luxury Transfer"
                />
                <CardImage
                  src={Image8}
                  href="./views/medical-evacuation"
                  product="Medical Evacuation"
                  alt="Medical Evacuation"
                />
              </div>
            </div>
          </div>
          <div className="w-full bg-light-gray text-semi-black px-40 min-h-screen py-20 sm:px-20 lg:px-32">
            <div className="grid lg:grid-cols-2 sm:grid-cols-1">
              <div className="relative sm:hidden lg:block lg:w-1/2">
                <div>
                  <img src={Image5} className="absolute" />
                </div>
                <div>
                  <img
                    src={Image6}
                    className="absolute top-[10%] left-[30%]"
                  />
                </div>
              </div>
              <div>
                <div>
                  <p className="text-xl text-gold">Benefit Of Service</p>
                  <h1 className="text-4xl font-semibold">
                    Benefit of Private Jet.
                  </h1>
                  <p className="my-4">
                    By constantly improving on the best. It’s in this spirit
                    that the Phenom 300E received further enhancements, becoming
                    the most successful.
                  </p>
                </div>
                <div className="mt-10">
                  <ul className="list-disc text-gold grid lg:grid-cols-2 sm:grid-cols-1 gap-6">
                    <li>
                      <div className="text-semi-black">
                        Full range of the latest generation jets, VIP aircraft
                        and helicopters for worldwide charter
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        We advise you on the best of the best, the newest and
                        most competitively priced private jets on the planet
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        Dedicated and experienced Aviation Consultants available
                        24 hours / 365 days
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        Creating a tailor made service to meet your own personal
                        requirements.
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        Choose your airport – choose your departure time
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        Fly from dedicated private jet airports, or choose from
                        main International airports, the choice is yours
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        Enjoy fine dining on board, choose from a selection of
                        international cuisine, Champagne, fine wines and full
                        bar included
                      </div>
                    </li>
                    <li>
                      <div className="text-semi-black">
                        Flying by Private Jet provides a flexible alternative to
                        the stress of flying with scheduled airlines
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="grid lg:grid-cols-2 sm:grid-cols-1 place-content-between gap-6 mt-20 2xl:mt-32">
              <div>
                <ul className="list-disc text-gold grid lg:grid-cols-2 sm:grid-cols-1 gap-6">
                  <li>
                    <div className="text-semi-black">
                      Arrive at the Private Jet Terminal just 20 minutes before
                      take-off
                    </div>
                  </li>
                  <li>
                    <div className="text-semi-black">
                      We use VIP lounge and swift check-in facilities
                    </div>
                  </li>
                  <li>
                    <div className="text-semi-black">
                      24hr Flight Tracking – we keep you informed of the status
                      of your flight around the clock
                    </div>
                  </li>
                  <li>
                    <div className="text-semi-black">
                      Our clients enjoy value for money and quality without
                      compromise. No other company comes close
                    </div>
                  </li>
                  <li>
                    <div className="text-semi-black">
                      Whatever you need, from chauffeur driven transportation to
                      custom branding the aircraft, everything is possible
                    </div>
                  </li>
                  <li>
                    <div className="text-semi-black">
                      We aim high. We have the means and experience to fulfil
                      every enquiry, every single time
                    </div>
                  </li>
                  <li>
                    <div className="text-semi-black">
                      Together with BIJB (Bandara Internasional Jawa Barat) we
                      provide Umrah flight as a solution for west java pilgrims,
                      departed from Kertajati Airport to Makkah and also Madinah
                    </div>
                  </li>
                </ul>
              </div>
              <div className="">
                <div>
                  <img src={Image3} className="aspect-1/1 bg-cover bg-center" />
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Section 3 */}

        {/* Sectiom 4 */}
        {/* <section id="our-deals">
          <div className="text-center">
            <p className="font-semibold text-lg">
              Jet <span className="text-gold">Safety</span>
            </p>
            <h1 className="text-4xl">Embraer P-300E Safety</h1>
          </div>
          <div className="grid lg:grid-cols-3 sm:grid-cols-1 place-content-between mt-10">
            <div>
              <div className="my-10">
                <div className="bg-light-purple rounded-full w-10 h-10 flex justify-center items-center text-2xl font-bold">
                  1
                </div>
                <h1 className="text-2xl">Punching way above its weight</h1>
                <p className="mt-5">
                  There is a very fast AVANCE L5 system for internet access and
                  it did not disappoint.
                </p>
              </div>
              <div>
                <div className="bg-light-purple rounded-full w-10 h-10 flex justify-center items-center text-2xl font-bold">
                  2
                </div>
                <h1 className="text-2xl">Punching way above its weight</h1>
                <p className="mt-5">
                  There is a very fast AVANCE L5 system for internet access and
                  it did not disappoint.
                </p>
              </div>
            </div>

            <div className="place-self-center relative">
              <div className="bg-light-purple rounded-full sm:w-60 sm:h-60 xl:w-96 xl:h-96 opacity-75 animate-ping duration-[5000] delay-[5000]"></div>
              <div className="absolute top-0">
                <img src={Image7} />
              </div>
            </div>

            <div>
              <div className="my-10">
                <div className="bg-light-purple rounded-full w-10 h-10 flex justify-center items-center text-2xl font-bold">
                  3
                </div>
                <h1 className="text-2xl">Punching way above its weight</h1>
                <p className="mt-5">
                  There is a very fast AVANCE L5 system for internet access and
                  it did not disappoint.
                </p>
              </div>
              <div>
                <div className="bg-light-purple rounded-full w-10 h-10 flex justify-center items-center text-2xl font-bold">
                  4
                </div>
                <h1 className="text-2xl">Punching way above its weight</h1>
                <p className="mt-5">
                  There is a very fast AVANCE L5 system for internet access and
                  it did not disappoint.
                </p>
              </div>
            </div>
          </div>
        </section> */}
        {/* Sectiom 4 */}

        {/* Section 5 */}
        <section id="packages">
          <div className="font-bold">
            <p className="text-sm uppercase">
              Luxury <span className="text-gold">Charter</span>
            </p>
            <div className="flex justify-between items-center w-full">
              <h1 className="text-4xl">Luxury Deals For You</h1>
              <Link
                href="./views/all-deals"
                className="px-4 py-3 rounded-full hover:bg-gold hover:text-white sm:text-[12px] md:text-base"
              >
                View All Deals
              </Link>
            </div>
          </div>
          <div className="mt-20">
            <div className="grid lg:grid-cols-4 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <CardImage
                src={Image1}
                product="Hawker-400XP"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./views/hawker-400xp"
              />
              <CardImage
                src={Image2}
                product="Hawker 800XP"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./views/hawker-800xp"
              />
              <CardImage
                src={Image3}
                product="Bell 407"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./views/bell-407"
              />
              <CardImage
                src={Image4}
                product="Bell 412"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./views/bell-412"
              />
            </div>
          </div>

          <div className="py-20">
            <blockquote className="text-3xl text-semi-black text-center">
              <span>"</span>
              <em>
                Giving unforgetable experience, air travel as time saving,
                cost-effective as possible.
              </em>
              <span>"</span>
            </blockquote>
          </div>
        </section>
        {/* Section 5 */}

        {/* Section-6 */}
        {/* <section id="our-blog">
          <div>
            <blockquote className="text-3xl text-semi-black text-center">
              <span>"</span>
              <em>
                Giving unforgetable experience, air travel as time saving,
                cost-effective as possible.
              </em>
              <span>"</span>
            </blockquote>
          </div>
          <div className="py-20">
            <div className="font-semibold text-center">
              <p className="text-xl">
                <span className="text-gold">JetBizz</span> Blog
              </p>
              <h1 className="text-4xl">Latest News From Us</h1>
            </div>
            <div className="mt-20">
              <div>
                <Swiper
                  spaceBetween={30}
                  loop={true}
                  autoplay={{
                    delay: 2500,
                    disableOnInteraction: false,
                  }}
                  slidesPerView={2}
                  modules={[Autoplay, Pagination, Navigation]}
                >
                  <SwiperSlide>
                    <SwiperImage
                      src={Image1}
                      alt="Image 1"
                      author="GW"
                      title="Loren ipsum dolor sit amet asu"
                      category="FPS"
                      href="./hawker-400xp"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <SwiperImage
                      src={Image2}
                      alt="Image 4"
                      author="GW"
                      title="Loren ipsum dolor sit amet asu"
                      category="FPS"
                      href="./hawker-400xp"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <SwiperImage
                      src={Image3}
                      alt="Image 4"
                      author="GW"
                      title="Loren ipsum dolor sit amet asu"
                      category="FPS"
                      href="./hawker-400xp"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <SwiperImage
                      src={Image4}
                      alt="Image 4"
                      author="GW"
                      title="Loren ipsum dolor sit amet asu"
                      category="FPS"
                      href="./hawker-400xp"
                    />
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
          </div>
        </section> */}
        {/* Section-6 */}
      </main>

      <Footer />
    </>
  );
}
