import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Header from "../layouts/Header";
import Footer from "../layouts/Footer";
import CardImage from "../components/CardImage";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
        <Head>
        <title>JetBizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicon/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicon/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicon/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicon/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicon/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicon/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/favicon/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicon/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicon/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicon/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <Header />

      <main>
        {/* Section 1 */}
        <section id="home">
          <div id="parallax">
            <div id="parallax-content">
              <p>#1 Private Jet Charter</p>
              <h1 className="xxs:text-3xl sm:text-5xl font-semibold text-white">
                Indonesian Private Charter with Global Coverage
              </h1>

              <p className="text-white">
                JetBizz is one of exclusive aviation services in Indonesia. Our
                professional focus is providing our clients exceptional jet
                charter service through making every air travel experience as
                time saving, enjoyable, and cost-effective as possible.
              </p>
            </div>
          </div>
        </section>
        {/* Section 1 */}

        {/* Section 2 */}
        <section id="services">
          <div id="overlay">
            <div id="overlay-image">
              <div id="overlay-1"></div>
              <div id="overlay-2"></div>
            </div>
            <div id="overlay-text">
              <p className="text-lg">Why Choose Us</p>

              <h1 className="sm:text-4xl xxs:text-3xl">
                Why Choose a Private Jet Charter?
              </h1>

              <p className="my-6 font-semibold">
                We provide aircraft charters to business professionals, to
                maximise their time efficiency. Today we provide aircraft
                charters to business professionals, to maximise their time
                efficiency.
              </p>

              <p className="my-6">
                As well as getting to fly to many different destinations as part
                of their job, airplane pilots get big discounts on, As well as
                getting to fly to many different destinations as part of their
                job, airplane pilots get big discounts on
              </p>

              <div id="overlay-text-list">
                <ul>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Flexible Schedule</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Excellent Advantages</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Save Your Time</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Luxury and Comfort</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>

                      <p>Safety and Confidential</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex justify-start items-center space-x-2">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 1024 1024"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="#000000"
                      >
                        <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            fill="#BC9B2F"
                            d="M512 896a384 384 0 100-768 384 384 0 000 768zm0 64a448 448 0 110-896 448 448 0 010 896z"
                          ></path>
                          <path
                            fill="#BC9B2F"
                            d="M745.344 361.344a32 32 0 0145.312 45.312l-288 288a32 32 0 01-45.312 0l-160-160a32 32 0 1145.312-45.312L480 626.752l265.344-265.408z"
                          ></path>
                        </g>
                      </svg>
                      <p>Many Airports</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section id="our-deals">
          <div className="font-bold">
            <p className="text-sm uppercase">
              Luxury <span className="text-gold">Charter</span>
            </p>
            <div className="sm:flex sm:justify-between sm:items-center xxs:items-start w-full xxs:flex-col sm:flex-row">
              <h1 className="sm:text-4xl xxs:text-3xl xxs:mb-4">Luxury Deals For You</h1>
              <Link
                href="./all-deals"
                className="px-4 py-3 rounded-full bg-gold duration-150 delay-150 hover:text-white xxs:text-[12px] sm:text-[12px] md:text-base"
              >
                View All Deals
              </Link>
            </div>
          </div>
          <div className="mt-20">
            <div className="grid xs:grid-cols-1 lg:grid-cols-4 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <CardImage
                src={"https://jetbizzaviation.com/images/Jets/Hawker-400XP/beechcraft-hawker-400xp.jpg"}
                product="Hawker-400XP"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./hawker-400xp"
              />
              <CardImage
                src={
                  "https://jetbizzaviation.com/images/Jets/Hawker 800XP/hawker-800xp-Exterior-NEW-jS.jpg"
                }
                product="Hawker 800XP"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./hawker-800xp"
              />
              <CardImage
                src={
                  "https://jetbizzaviation.com/images/Helicopters/BELL 407/helicopter-bell_407-1024x768.jpg"
                }
                product="Bell 407"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./bell-407"
              />
              <CardImage
                src={
                  "https://jetbizzaviation.com/images/Helicopters/BELL 412/Bell-412EP-e1427082029160-1200x718.jpg"
                }
                product="Bell 412"
                type="Legacy 600"
                capacity="4-8 Seats"
                href="./bell-412"
              />
            </div>
          </div>

          <div className="py-20">
            <blockquote className="sm:text-3xl text-semi-black text-center">
              <span>"</span>
              <em>
                Giving unforgetable experience, air travel as time saving,
                cost-effective as possible.
              </em>
              <span>"</span>
            </blockquote>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
