import Image from "next/image";
import Header from "@/layouts/Header";

import Footer from "@/layouts/Footer";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Autoplay, Navigation, Pagination } from "swiper";
import Head from "next/head";
import Contact from "@/components/Contact";
import CardImage from "@/components/CardImage";

export default function AddDeals() {
  return (
    <>
      <Head>
        <title>JetBizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicon/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicon/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicon/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicon/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicon/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicon/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/favicon/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicon/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicon/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicon/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <Header />

      <main>
        <section>
          <div className="min-h-screen bg-white py-20 text-semi-black">
            <div className="mx-10 lg:mx-32 my-20 md:mx-20">
              <div className="font-bold text-semi-black mb-10">
                <p className="uppercase">
                  Our <span className="text-gold">Luxury</span> Jets
                </p>
                <h2 className="text-2xl w-2/3">From 5 up to 40 seater</h2>
                <p>
                  executive jets with luxurious seating configuration and
                  in-flight facilities.
                </p>
              </div>

              <div>
                <div className="grid lg:grid-cols-4 xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                  <CardImage
                    src={"images/Jets/Hawker-400XP/Starmedevac-hawker-400.jpg"}
                    product="Hawker-400XP"
                    capacity="6 Seats"
                    href="./hawker-400xp"
                  />
                  <CardImage
                    src={"images/Jets/Hawker 800XP/hawker-800-xp-1.jpg"}
                    product="Hawker 800XP"
                    capacity="8 Seats"
                    href="./hawker-800xp"
                  />
                  <CardImage
                    src={"images/Jets/Hawker 900XP/Hawker-900XP-Ext-JS.webp"}
                    product="Hawker 900XP"
                    capacity="8 Seats"
                    href="./hawker-900xp"
                  />
                  <CardImage
                    src={"images/Jets/BAE 146/BAe-146.jpg"}
                    product="BAE 146 Series"
                    capacity="70 - 112 Seats"
                    href="./bae-146-series"
                  />
                  <CardImage
                    src={
                      "images/Jets/Beechcraft King Air 200/1979-Beechcraft-King-Air-200-01.jpg"
                    }
                    product="Beechcraft King Air 200"
                    capacity="6 Seats"
                    href="./beechcraft-king-air-200"
                  />
                  <CardImage
                    src={
                      "images/Jets/Beechcraft King Air 350/Beechcraft-King-Air-350i-1090x500.jpg"
                    }
                    product="Beechcraft King Air 350"
                    capacity="9-11 Seats"
                    href="./beechcraft-king-air-350"
                  />
                  <CardImage
                    src={"images/Jets/Beechcraft 1900D/1574693448.jpg"}
                    product="Beechcraft 1900D"
                    capacity="19 Seats"
                    href="./beechcraft-1900-d"
                  />
                  <CardImage
                    src={
                      "images/Jets/Beechjet 400a/Hawker-Beechcraft-Beechjet-400A.jpg"
                    }
                    product="Beechjet 400A"
                    capacity="7-9 Seats"
                    href="./beechjet-400a"
                  />
                  <CardImage
                    src={
                      "images/Jets/Cessna Citation XLS/Citation_XLS_Ext3-3-1024x723.jpg"
                    }
                    product="Cessna Citation XLS"
                    capacity="9 Seats"
                    href="./cessna-citation-xls"
                  />
                  <CardImage
                    src={
                      "images/Jets/Embraer ERJ 135/Embraer-ERJ-135BJ-Legacy-650-1.jpg"
                    }
                    product="Embraer ERJ 135"
                    capacity="16 Seats"
                    href="./embraer-erj-135"
                  />
                  <CardImage
                    src={
                      "images/Jets/Embraer Phenom 300/AeroBT-aero-bk-embraer-Phenom-300_2880x1440.jpg"
                    }
                    product="Embraer Phenom 300"
                    capacity="7 Seats"
                    href="./embraer-phenom-300"
                  />
                  <CardImage
                    src={
                      "images/Jets/Embraer Legacy 600/AeroBT-Legacy600_2880x1440.jpg"
                    }
                    product="Embraer Legacy 600"
                    capacity="14 Seats"
                    href="./embraer-legacy-600"
                  />
                  <CardImage
                    src={"images/Jets/Fokker 50/72434_palf502_412926.jpg"}
                    product="Fokker 50"
                    capacity="46 Seats"
                    href="./fokker-50"
                  />
                  <CardImage
                    src={"images/Jets/Fokker 70/fokker-70-1.webp"}
                    product="Fokker 70"
                    capacity="85 Seats"
                    href="./fokker-70"
                  />
                  <CardImage
                    src={
                      "images/Jets/Fokker 100/Fokker-Executive-Jet-indo-jet-charter.jpg"
                    }
                    product="Fokker 100"
                    capacity="107 Seats"
                    href="./fokker-100"
                  />
                  <CardImage
                    src={"images/Jets/Gulfstream IV SP/gulfstream-iv-iv-sp.jpg"}
                    product="Gulfstream IV SP"
                    capacity="14 Seats"
                    href="./gulfstream-iv-sp"
                  />
                  <CardImage
                    src={"images/Jets/Gulfstream 550/APERTUS+Jordon+G550.jpg"}
                    product="Gulfstream 550"
                    capacity="19 Seats"
                    href="./gulfstream-550"
                  />
                  <CardImage
                    src={"images/Jets/Gulfstream 500/1.jpeg"}
                    product="Gulfstream 500"
                    capacity="16+ Seats"
                    href="./gulfstream-500"
                  />
                  <CardImage
                    src={"images/Jets/Learjet 31A/Learjet31A_1.jpg"}
                    product="Learjet 31 A"
                    capacity="6 Seats"
                    href="./learjet-31a"
                  />
                </div>

                <div className="my-20">
                  <div className="font-bold text-semi-black mb-10">
                    <p className="uppercase">
                      Our <span className="text-gold">Luxury</span> Helicopters
                    </p>
                    <h2 className="text-2xl w-2/3">From 5 up to 15 seater</h2>
                    <p>
                      executive helicopters with luxurious seating configuration
                      and in-flight facilities.
                    </p>
                  </div>

                  <div>
                    <div className="grid lg:grid-cols-4 xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                      <CardImage
                        src={
                          "images/Helicopters/Airbus Helicopter EC/84518_1660386405.webp"
                        }
                        product="Airbus Helicopter EC"
                        capacity="8 Seats"
                        href="./airbus-helicopter-ec"
                      />
                      <CardImage
                        src={"images/Helicopters/BELL 206 L 4/18012016-29.jpg"}
                        product="Bell 206 L-4"
                        capacity="4 Seats"
                        href="./bell-206-l-4"
                      />
                      <CardImage
                        src={
                          "images/Helicopters/BELL 407/helicopter-bell_407-1024x768.jpg"
                        }
                        product="Bell 407"
                        capacity="5 Seats"
                        href="./bell-407"
                      />
                      <CardImage
                        src={
                          "images/Helicopters/BELL 412/Bell-412EP-e1427082029160-1200x718.jpg"
                        }
                        product="Bell 412"
                        capacity="6 Seats"
                        href="./bell-412"
                      />
                      <CardImage
                        src={"images/Helicopters/BELL 429/download.jpeg"}
                        product="Bell 429"
                        capacity="5 Seats"
                        href="./bell-429"
                      />
                      <CardImage
                        src={"images/Helicopters/BK117A-4/maxresdefault.jpg"}
                        product="BK 117A-4"
                        capacity="up to 10 Seats"
                        href="./bk-117a-4"
                      />
                      <CardImage
                        src={
                          "images/Helicopters/Eurocopter AS350B-3/AS350B3+-Squirrel-EN.jpg"
                        }
                        product="Eurocopter AS350-B3"
                        capacity="4 Seats"
                        href="./eurocopter-as350-b3"
                      />
                      <CardImage
                        src={"images/Helicopters/Eurocopter B155-B1/1.webp"}
                        product="Eurocopter B155-B1"
                        capacity="4-8 Seats"
                        href="./eurocopter-b155-b1"
                      />
                      <CardImage
                        src={
                          "images/Helicopters/Kamov KA-32A/95e8d6de6e842c7859e01faf026c477a_900.jpg"
                        }
                        product="Kamov KA-32A"
                        capacity="13 Seats"
                        href="./kamov-ka-32a"
                      />
                      <CardImage
                        src={"images/Helicopters/MI 171/mi-171e_uganda.jpg"}
                        product="MI 171"
                        capacity="4-8 Seats"
                        href="./mi-171"
                      />
                      <CardImage
                        src={
                          "images/Helicopters/MI 8/Mil_Mi-8P,_Baltic_Airlines_(cropped).jpg"
                        }
                        product="MI 8"
                        capacity="4-8 Seats"
                        href="./mi-8"
                      />
                      <CardImage
                        src={"images/Helicopters/MI 26/miil-mi-26-1.jpg"}
                        product="MI 26"
                        capacity="4-8 Seats"
                        href="./mi-26"
                      />
                      <CardImage
                        src={"images/Helicopters/Super Puma/superpuma-4.jpg"}
                        product="Super Puma"
                        capacity="20-24 Seats"
                        href="./super-puma"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <Contact />
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
